version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/training_diary
    entrypoint: sh ./run.sh
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"

volumes:
  postgres_data: