version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/training_diary
    entrypoint: sh ./run.sh
    depends_on:
      - db
      - mail

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"

  mail:
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: ${RELAY_HOST}
      RELAY_PORT: ${RELAY_PORT}
      RELAY_USERNAME: ${RELAY_USERNAME}
      EMAIL_HOST_PASSWORD: ${RELAY_PASSWORD}

  celery:
    build: .
    command: celery -A training_diary worker -l INFO
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7.0-alpine

volumes:
  postgres_data: