# Generated by Django 4.1.4 on 2022-12-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loaders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='reports/%Y_%m_%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('moving_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avg_pace', models.CharField(max_length=50, null=True)),
                ('started_at', models.DateTimeField()),
                ('description', models.TextField(null=True)),
                ('file_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loaders.fileloader')),
            ],
        ),
    ]
